use crate::db::Index;

pub enum Tag {
    /// Unknown tag
    NOT_FOUND = librpm::rpmTag_e_RPMTAG_NOT_FOUND as isize,

    /// Current image
    HEADERIMAGE = librpm::rpmTag_e_RPMTAG_HEADERIMAGE as isize,

    /// Signatures
    HEADERSIGNATURES = librpm::rpmTag_e_RPMTAG_HEADERSIGNATURES as isize,

    /// Original image
    HEADERIMMUTABLE = librpm::rpmTag_e_RPMTAG_HEADERIMMUTABLE as isize,

    /// Regions
    HEADERREGIONS = librpm::rpmTag_e_RPMTAG_HEADERREGIONS as isize,

    /// I18N string locales
    HEADERI18NTABLE = librpm::rpmTag_e_RPMTAG_HEADERI18NTABLE as isize,
    SIG_BASE = librpm::rpmTag_e_RPMTAG_SIG_BASE as isize,
    SIGSIZE = librpm::rpmTag_e_RPMTAG_SIGSIZE as isize,
    SIGPGP = librpm::rpmTag_e_RPMTAG_SIGPGP as isize,
    SIGMD5 = librpm::rpmTag_e_RPMTAG_SIGMD5 as isize,
    SIGGPG = librpm::rpmTag_e_RPMTAG_SIGGPG as isize,
    PUBKEYS = librpm::rpmTag_e_RPMTAG_PUBKEYS as isize,
    DSAHEADER = librpm::rpmTag_e_RPMTAG_DSAHEADER as isize,
    RSAHEADER = librpm::rpmTag_e_RPMTAG_RSAHEADER as isize,
    SHA1HEADER = librpm::rpmTag_e_RPMTAG_SHA1HEADER as isize,
    LONGSIGSIZE = librpm::rpmTag_e_RPMTAG_LONGSIGSIZE as isize,
    LONGARCHIVESIZE = librpm::rpmTag_e_RPMTAG_LONGARCHIVESIZE as isize,
    NAME = librpm::rpmTag_e_RPMTAG_NAME as isize,
    VERSION = librpm::rpmTag_e_RPMTAG_VERSION as isize,
    RELEASE = librpm::rpmTag_e_RPMTAG_RELEASE as isize,
    EPOCH = librpm::rpmTag_e_RPMTAG_EPOCH as isize,
    SUMMARY = librpm::rpmTag_e_RPMTAG_SUMMARY as isize,
    DESCRIPTION = librpm::rpmTag_e_RPMTAG_DESCRIPTION as isize,
    BUILDTIME = librpm::rpmTag_e_RPMTAG_BUILDTIME as isize,
    BUILDHOST = librpm::rpmTag_e_RPMTAG_BUILDHOST as isize,
    INSTALLTIME = librpm::rpmTag_e_RPMTAG_INSTALLTIME as isize,
    SIZE = librpm::rpmTag_e_RPMTAG_SIZE as isize,
    DISTRIBUTION = librpm::rpmTag_e_RPMTAG_DISTRIBUTION as isize,
    VENDOR = librpm::rpmTag_e_RPMTAG_VENDOR as isize,
    GIF = librpm::rpmTag_e_RPMTAG_GIF as isize,
    XPM = librpm::rpmTag_e_RPMTAG_XPM as isize,
    LICENSE = librpm::rpmTag_e_RPMTAG_LICENSE as isize,
    PACKAGER = librpm::rpmTag_e_RPMTAG_PACKAGER as isize,
    GROUP = librpm::rpmTag_e_RPMTAG_GROUP as isize,
    CHANGELOG = librpm::rpmTag_e_RPMTAG_CHANGELOG as isize,
    SOURCE = librpm::rpmTag_e_RPMTAG_SOURCE as isize,
    PATCH = librpm::rpmTag_e_RPMTAG_PATCH as isize,
    URL = librpm::rpmTag_e_RPMTAG_URL as isize,
    OS = librpm::rpmTag_e_RPMTAG_OS as isize,
    ARCH = librpm::rpmTag_e_RPMTAG_ARCH as isize,
    PREIN = librpm::rpmTag_e_RPMTAG_PREIN as isize,
    POSTIN = librpm::rpmTag_e_RPMTAG_POSTIN as isize,
    PREUN = librpm::rpmTag_e_RPMTAG_PREUN as isize,
    POSTUN = librpm::rpmTag_e_RPMTAG_POSTUN as isize,
    FILESIZES = librpm::rpmTag_e_RPMTAG_FILESIZES as isize,
    FILESTATES = librpm::rpmTag_e_RPMTAG_FILESTATES as isize,
    FILEMODES = librpm::rpmTag_e_RPMTAG_FILEMODES as isize,
    FILERDEVS = librpm::rpmTag_e_RPMTAG_FILERDEVS as isize,
    FILEMTIMES = librpm::rpmTag_e_RPMTAG_FILEMTIMES as isize,
    FILEDIGESTS = librpm::rpmTag_e_RPMTAG_FILEDIGESTS as isize,
    FILELINKTOS = librpm::rpmTag_e_RPMTAG_FILELINKTOS as isize,
    FILEFLAGS = librpm::rpmTag_e_RPMTAG_FILEFLAGS as isize,
    ROOT = librpm::rpmTag_e_RPMTAG_ROOT as isize,
    FILEUSERNAME = librpm::rpmTag_e_RPMTAG_FILEUSERNAME as isize,
    FILEGROUPNAME = librpm::rpmTag_e_RPMTAG_FILEGROUPNAME as isize,
    ICON = librpm::rpmTag_e_RPMTAG_ICON as isize,
    SOURCERPM = librpm::rpmTag_e_RPMTAG_SOURCERPM as isize,
    FILEVERIFYFLAGS = librpm::rpmTag_e_RPMTAG_FILEVERIFYFLAGS as isize,
    ARCHIVESIZE = librpm::rpmTag_e_RPMTAG_ARCHIVESIZE as isize,
    PROVIDENAME = librpm::rpmTag_e_RPMTAG_PROVIDENAME as isize,
    REQUIREFLAGS = librpm::rpmTag_e_RPMTAG_REQUIREFLAGS as isize,
    REQUIRENAME = librpm::rpmTag_e_RPMTAG_REQUIRENAME as isize,
    REQUIREVERSION = librpm::rpmTag_e_RPMTAG_REQUIREVERSION as isize,
    NOSOURCE = librpm::rpmTag_e_RPMTAG_NOSOURCE as isize,
    NOPATCH = librpm::rpmTag_e_RPMTAG_NOPATCH as isize,
    CONFLICTFLAGS = librpm::rpmTag_e_RPMTAG_CONFLICTFLAGS as isize,
    CONFLICTNAME = librpm::rpmTag_e_RPMTAG_CONFLICTNAME as isize,
    CONFLICTVERSION = librpm::rpmTag_e_RPMTAG_CONFLICTVERSION as isize,
    DEFAULTPREFIX = librpm::rpmTag_e_RPMTAG_DEFAULTPREFIX as isize,
    BUILDROOT = librpm::rpmTag_e_RPMTAG_BUILDROOT as isize,
    INSTALLPREFIX = librpm::rpmTag_e_RPMTAG_INSTALLPREFIX as isize,
    EXCLUDEARCH = librpm::rpmTag_e_RPMTAG_EXCLUDEARCH as isize,
    EXCLUDEOS = librpm::rpmTag_e_RPMTAG_EXCLUDEOS as isize,
    EXCLUSIVEARCH = librpm::rpmTag_e_RPMTAG_EXCLUSIVEARCH as isize,
    EXCLUSIVEOS = librpm::rpmTag_e_RPMTAG_EXCLUSIVEOS as isize,
    AUTOREQPROV = librpm::rpmTag_e_RPMTAG_AUTOREQPROV as isize,
    RPMVERSION = librpm::rpmTag_e_RPMTAG_RPMVERSION as isize,
    TRIGGERSCRIPTS = librpm::rpmTag_e_RPMTAG_TRIGGERSCRIPTS as isize,
    TRIGGERNAME = librpm::rpmTag_e_RPMTAG_TRIGGERNAME as isize,
    TRIGGERVERSION = librpm::rpmTag_e_RPMTAG_TRIGGERVERSION as isize,
    TRIGGERFLAGS = librpm::rpmTag_e_RPMTAG_TRIGGERFLAGS as isize,
    TRIGGERINDEX = librpm::rpmTag_e_RPMTAG_TRIGGERINDEX as isize,
    VERIFYSCRIPT = librpm::rpmTag_e_RPMTAG_VERIFYSCRIPT as isize,
    CHANGELOGTIME = librpm::rpmTag_e_RPMTAG_CHANGELOGTIME as isize,
    CHANGELOGNAME = librpm::rpmTag_e_RPMTAG_CHANGELOGNAME as isize,
    CHANGELOGTEXT = librpm::rpmTag_e_RPMTAG_CHANGELOGTEXT as isize,
    PREREQ = librpm::rpmTag_e_RPMTAG_PREREQ as isize,
    PREINPROG = librpm::rpmTag_e_RPMTAG_PREINPROG as isize,
    POSTINPROG = librpm::rpmTag_e_RPMTAG_POSTINPROG as isize,
    PREUNPROG = librpm::rpmTag_e_RPMTAG_PREUNPROG as isize,
    POSTUNPROG = librpm::rpmTag_e_RPMTAG_POSTUNPROG as isize,
    BUILDARCHS = librpm::rpmTag_e_RPMTAG_BUILDARCHS as isize,
    OBSOLETENAME = librpm::rpmTag_e_RPMTAG_OBSOLETENAME as isize,
    VERIFYSCRIPTPROG = librpm::rpmTag_e_RPMTAG_VERIFYSCRIPTPROG as isize,
    TRIGGERSCRIPTPROG = librpm::rpmTag_e_RPMTAG_TRIGGERSCRIPTPROG as isize,
    DOCDIR = librpm::rpmTag_e_RPMTAG_DOCDIR as isize,
    COOKIE = librpm::rpmTag_e_RPMTAG_COOKIE as isize,
    FILEDEVICES = librpm::rpmTag_e_RPMTAG_FILEDEVICES as isize,
    FILEINODES = librpm::rpmTag_e_RPMTAG_FILEINODES as isize,
    FILELANGS = librpm::rpmTag_e_RPMTAG_FILELANGS as isize,
    PREFIXES = librpm::rpmTag_e_RPMTAG_PREFIXES as isize,
    INSTPREFIXES = librpm::rpmTag_e_RPMTAG_INSTPREFIXES as isize,
    TRIGGERIN = librpm::rpmTag_e_RPMTAG_TRIGGERIN as isize,
    TRIGGERUN = librpm::rpmTag_e_RPMTAG_TRIGGERUN as isize,
    TRIGGERPOSTUN = librpm::rpmTag_e_RPMTAG_TRIGGERPOSTUN as isize,
    AUTOREQ = librpm::rpmTag_e_RPMTAG_AUTOREQ as isize,
    AUTOPROV = librpm::rpmTag_e_RPMTAG_AUTOPROV as isize,
    CAPABILITY = librpm::rpmTag_e_RPMTAG_CAPABILITY as isize,
    SOURCEPACKAGE = librpm::rpmTag_e_RPMTAG_SOURCEPACKAGE as isize,
    BUILDPREREQ = librpm::rpmTag_e_RPMTAG_BUILDPREREQ as isize,
    BUILDREQUIRES = librpm::rpmTag_e_RPMTAG_BUILDREQUIRES as isize,
    BUILDCONFLICTS = librpm::rpmTag_e_RPMTAG_BUILDCONFLICTS as isize,
    PROVIDEFLAGS = librpm::rpmTag_e_RPMTAG_PROVIDEFLAGS as isize,
    PROVIDEVERSION = librpm::rpmTag_e_RPMTAG_PROVIDEVERSION as isize,
    DIRINDEXES = librpm::rpmTag_e_RPMTAG_DIRINDEXES as isize,
    BASENAMES = librpm::rpmTag_e_RPMTAG_BASENAMES as isize,
    DIRNAMES = librpm::rpmTag_e_RPMTAG_DIRNAMES as isize,
    ORIGDIRINDEXES = librpm::rpmTag_e_RPMTAG_ORIGDIRINDEXES as isize,
    ORIGBASENAMES = librpm::rpmTag_e_RPMTAG_ORIGBASENAMES as isize,
    ORIGDIRNAMES = librpm::rpmTag_e_RPMTAG_ORIGDIRNAMES as isize,
    OPTFLAGS = librpm::rpmTag_e_RPMTAG_OPTFLAGS as isize,
    DISTURL = librpm::rpmTag_e_RPMTAG_DISTURL as isize,
    PAYLOADFORMAT = librpm::rpmTag_e_RPMTAG_PAYLOADFORMAT as isize,
    PAYLOADCOMPRESSOR = librpm::rpmTag_e_RPMTAG_PAYLOADCOMPRESSOR as isize,
    PAYLOADFLAGS = librpm::rpmTag_e_RPMTAG_PAYLOADFLAGS as isize,
    INSTALLCOLOR = librpm::rpmTag_e_RPMTAG_INSTALLCOLOR as isize,
    INSTALLTID = librpm::rpmTag_e_RPMTAG_INSTALLTID as isize,
    REMOVETID = librpm::rpmTag_e_RPMTAG_REMOVETID as isize,
    PLATFORM = librpm::rpmTag_e_RPMTAG_PLATFORM as isize,
    PATCHESNAME = librpm::rpmTag_e_RPMTAG_PATCHESNAME as isize,
    PATCHESFLAGS = librpm::rpmTag_e_RPMTAG_PATCHESFLAGS as isize,
    PATCHESVERSION = librpm::rpmTag_e_RPMTAG_PATCHESVERSION as isize,
    FILECOLORS = librpm::rpmTag_e_RPMTAG_FILECOLORS as isize,
    FILECLASS = librpm::rpmTag_e_RPMTAG_FILECLASS as isize,
    CLASSDICT = librpm::rpmTag_e_RPMTAG_CLASSDICT as isize,
    FILEDEPENDSX = librpm::rpmTag_e_RPMTAG_FILEDEPENDSX as isize,
    FILEDEPENDSN = librpm::rpmTag_e_RPMTAG_FILEDEPENDSN as isize,
    DEPENDSDICT = librpm::rpmTag_e_RPMTAG_DEPENDSDICT as isize,
    SOURCEPKGID = librpm::rpmTag_e_RPMTAG_SOURCEPKGID as isize,
    FSCONTEXTS = librpm::rpmTag_e_RPMTAG_FSCONTEXTS as isize,
    RECONTEXTS = librpm::rpmTag_e_RPMTAG_RECONTEXTS as isize,
    POLICIES = librpm::rpmTag_e_RPMTAG_POLICIES as isize,
    PRETRANS = librpm::rpmTag_e_RPMTAG_PRETRANS as isize,
    POSTTRANS = librpm::rpmTag_e_RPMTAG_POSTTRANS as isize,
    PRETRANSPROG = librpm::rpmTag_e_RPMTAG_PRETRANSPROG as isize,
    POSTTRANSPROG = librpm::rpmTag_e_RPMTAG_POSTTRANSPROG as isize,
    DISTTAG = librpm::rpmTag_e_RPMTAG_DISTTAG as isize,
    //SUGGESTNAME = librpm::rpmTag_e_RPMTAG_SUGGESTNAME as isize,
    //SUGGESTVERSION = librpm::rpmTag_e_RPMTAG_SUGGESTVERSION as isize,
    //SUGGESTFLAGS = librpm::rpmTag_e_RPMTAG_SUGGESTFLAGS as isize,
    //ENHANCENAME = librpm::rpmTag_e_RPMTAG_ENHANCENAME as isize,
    //ENHANCEVERSION = librpm::rpmTag_e_RPMTAG_ENHANCEVERSION as isize,
    //ENHANCEFLAGS = librpm::rpmTag_e_RPMTAG_ENHANCEFLAGS as isize,
    PRIORITY = librpm::rpmTag_e_RPMTAG_PRIORITY as isize,
    CVSID = librpm::rpmTag_e_RPMTAG_CVSID as isize,
    BLINKPKGID = librpm::rpmTag_e_RPMTAG_BLINKPKGID as isize,
    BLINKHDRID = librpm::rpmTag_e_RPMTAG_BLINKHDRID as isize,
    BLINKNEVRA = librpm::rpmTag_e_RPMTAG_BLINKNEVRA as isize,
    FLINKPKGID = librpm::rpmTag_e_RPMTAG_FLINKPKGID as isize,
    FLINKHDRID = librpm::rpmTag_e_RPMTAG_FLINKHDRID as isize,
    FLINKNEVRA = librpm::rpmTag_e_RPMTAG_FLINKNEVRA as isize,
    PACKAGEORIGIN = librpm::rpmTag_e_RPMTAG_PACKAGEORIGIN as isize,
    TRIGGERPREIN = librpm::rpmTag_e_RPMTAG_TRIGGERPREIN as isize,
    BUILDSUGGESTS = librpm::rpmTag_e_RPMTAG_BUILDSUGGESTS as isize,
    BUILDENHANCES = librpm::rpmTag_e_RPMTAG_BUILDENHANCES as isize,
    SCRIPTSTATES = librpm::rpmTag_e_RPMTAG_SCRIPTSTATES as isize,
    SCRIPTMETRICS = librpm::rpmTag_e_RPMTAG_SCRIPTMETRICS as isize,
    BUILDCPUCLOCK = librpm::rpmTag_e_RPMTAG_BUILDCPUCLOCK as isize,
    FILEDIGESTALGOS = librpm::rpmTag_e_RPMTAG_FILEDIGESTALGOS as isize,
    VARIANTS = librpm::rpmTag_e_RPMTAG_VARIANTS as isize,
    XMAJOR = librpm::rpmTag_e_RPMTAG_XMAJOR as isize,
    XMINOR = librpm::rpmTag_e_RPMTAG_XMINOR as isize,
    REPOTAG = librpm::rpmTag_e_RPMTAG_REPOTAG as isize,
    KEYWORDS = librpm::rpmTag_e_RPMTAG_KEYWORDS as isize,
    BUILDPLATFORMS = librpm::rpmTag_e_RPMTAG_BUILDPLATFORMS as isize,
    PACKAGECOLOR = librpm::rpmTag_e_RPMTAG_PACKAGECOLOR as isize,
    PACKAGEPREFCOLOR = librpm::rpmTag_e_RPMTAG_PACKAGEPREFCOLOR as isize,
    XATTRSDICT = librpm::rpmTag_e_RPMTAG_XATTRSDICT as isize,
    FILEXATTRSX = librpm::rpmTag_e_RPMTAG_FILEXATTRSX as isize,
    DEPATTRSDICT = librpm::rpmTag_e_RPMTAG_DEPATTRSDICT as isize,
    CONFLICTATTRSX = librpm::rpmTag_e_RPMTAG_CONFLICTATTRSX as isize,
    OBSOLETEATTRSX = librpm::rpmTag_e_RPMTAG_OBSOLETEATTRSX as isize,
    PROVIDEATTRSX = librpm::rpmTag_e_RPMTAG_PROVIDEATTRSX as isize,
    REQUIREATTRSX = librpm::rpmTag_e_RPMTAG_REQUIREATTRSX as isize,
    BUILDPROVIDES = librpm::rpmTag_e_RPMTAG_BUILDPROVIDES as isize,
    BUILDOBSOLETES = librpm::rpmTag_e_RPMTAG_BUILDOBSOLETES as isize,
    DBINSTANCE = librpm::rpmTag_e_RPMTAG_DBINSTANCE as isize,
    NVRA = librpm::rpmTag_e_RPMTAG_NVRA as isize,
    FILENAMES = librpm::rpmTag_e_RPMTAG_FILENAMES as isize,
    FILEPROVIDE = librpm::rpmTag_e_RPMTAG_FILEPROVIDE as isize,
    FILEREQUIRE = librpm::rpmTag_e_RPMTAG_FILEREQUIRE as isize,
    FSNAMES = librpm::rpmTag_e_RPMTAG_FSNAMES as isize,
    FSSIZES = librpm::rpmTag_e_RPMTAG_FSSIZES as isize,
    TRIGGERCONDS = librpm::rpmTag_e_RPMTAG_TRIGGERCONDS as isize,
    TRIGGERTYPE = librpm::rpmTag_e_RPMTAG_TRIGGERTYPE as isize,
    ORIGFILENAMES = librpm::rpmTag_e_RPMTAG_ORIGFILENAMES as isize,
    LONGFILESIZES = librpm::rpmTag_e_RPMTAG_LONGFILESIZES as isize,
    LONGSIZE = librpm::rpmTag_e_RPMTAG_LONGSIZE as isize,
    FILECAPS = librpm::rpmTag_e_RPMTAG_FILECAPS as isize,
    FILEDIGESTALGO = librpm::rpmTag_e_RPMTAG_FILEDIGESTALGO as isize,
    BUGURL = librpm::rpmTag_e_RPMTAG_BUGURL as isize,
    EVR = librpm::rpmTag_e_RPMTAG_EVR as isize,
    NVR = librpm::rpmTag_e_RPMTAG_NVR as isize,
    NEVR = librpm::rpmTag_e_RPMTAG_NEVR as isize,
    NEVRA = librpm::rpmTag_e_RPMTAG_NEVRA as isize,
    HEADERCOLOR = librpm::rpmTag_e_RPMTAG_HEADERCOLOR as isize,
    VERBOSE = librpm::rpmTag_e_RPMTAG_VERBOSE as isize,
    EPOCHNUM = librpm::rpmTag_e_RPMTAG_EPOCHNUM as isize,
    PREINFLAGS = librpm::rpmTag_e_RPMTAG_PREINFLAGS as isize,
    POSTINFLAGS = librpm::rpmTag_e_RPMTAG_POSTINFLAGS as isize,
    PREUNFLAGS = librpm::rpmTag_e_RPMTAG_PREUNFLAGS as isize,
    POSTUNFLAGS = librpm::rpmTag_e_RPMTAG_POSTUNFLAGS as isize,
    PRETRANSFLAGS = librpm::rpmTag_e_RPMTAG_PRETRANSFLAGS as isize,
    POSTTRANSFLAGS = librpm::rpmTag_e_RPMTAG_POSTTRANSFLAGS as isize,
    VERIFYSCRIPTFLAGS = librpm::rpmTag_e_RPMTAG_VERIFYSCRIPTFLAGS as isize,
    TRIGGERSCRIPTFLAGS = librpm::rpmTag_e_RPMTAG_TRIGGERSCRIPTFLAGS as isize,
    COLLECTIONS = librpm::rpmTag_e_RPMTAG_COLLECTIONS as isize,
    POLICYNAMES = librpm::rpmTag_e_RPMTAG_POLICYNAMES as isize,
    POLICYTYPES = librpm::rpmTag_e_RPMTAG_POLICYTYPES as isize,
    POLICYTYPESINDEXES = librpm::rpmTag_e_RPMTAG_POLICYTYPESINDEXES as isize,
    POLICYFLAGS = librpm::rpmTag_e_RPMTAG_POLICYFLAGS as isize,
    VCS = librpm::rpmTag_e_RPMTAG_VCS as isize,
    ORDERNAME = librpm::rpmTag_e_RPMTAG_ORDERNAME as isize,
    ORDERVERSION = librpm::rpmTag_e_RPMTAG_ORDERVERSION as isize,
    ORDERFLAGS = librpm::rpmTag_e_RPMTAG_ORDERFLAGS as isize,
    MSSFMANIFEST = librpm::rpmTag_e_RPMTAG_MSSFMANIFEST as isize,
    MSSFDOMAIN = librpm::rpmTag_e_RPMTAG_MSSFDOMAIN as isize,
    INSTFILENAMES = librpm::rpmTag_e_RPMTAG_INSTFILENAMES as isize,
    REQUIRENEVRS = librpm::rpmTag_e_RPMTAG_REQUIRENEVRS as isize,
    PROVIDENEVRS = librpm::rpmTag_e_RPMTAG_PROVIDENEVRS as isize,
    OBSOLETENEVRS = librpm::rpmTag_e_RPMTAG_OBSOLETENEVRS as isize,
    CONFLICTNEVRS = librpm::rpmTag_e_RPMTAG_CONFLICTNEVRS as isize,
    FILENLINKS = librpm::rpmTag_e_RPMTAG_FILENLINKS as isize,
}


pub enum TagType {
    NULL = librpm::rpmTagType_e_RPM_NULL_TYPE as isize,
    CHAR = librpm::rpmTagType_e_RPM_CHAR_TYPE as isize,
    INT8 = librpm::rpmTagType_e_RPM_INT8_TYPE as isize,
    INT16 = librpm::rpmTagType_e_RPM_INT16_TYPE as isize,
    INT32 = librpm::rpmTagType_e_RPM_INT32_TYPE as isize,
    INT64 = librpm::rpmTagType_e_RPM_INT64_TYPE as isize,
    STRING = librpm::rpmTagType_e_RPM_STRING_TYPE as isize,
    BIN = librpm::rpmTagType_e_RPM_BIN_TYPE as isize,
    STRING_ARRAY = librpm::rpmTagType_e_RPM_STRING_ARRAY_TYPE as isize,
    I18NSTRING = librpm::rpmTagType_e_RPM_I18NSTRING_TYPE as isize,   
}

pub enum DBIndexTag {
    PACKAGES = librpm::rpmDbiTag_e_RPMDBI_PACKAGES as isize,
    LABEL = librpm::rpmDbiTag_e_RPMDBI_LABEL as isize,
    NAME = librpm::rpmDbiTag_e_RPMDBI_NAME as isize,
    BASENAMES = librpm::rpmDbiTag_e_RPMDBI_BASENAMES as isize,
    GROUP = librpm::rpmDbiTag_e_RPMDBI_GROUP as isize,
    REQUIRENAME = librpm::rpmDbiTag_e_RPMDBI_REQUIRENAME as isize,
    PROVIDENAME = librpm::rpmDbiTag_e_RPMDBI_PROVIDENAME as isize,
    CONFLICTNAME = librpm::rpmDbiTag_e_RPMDBI_CONFLICTNAME as isize,
    OBSOLETENAME = librpm::rpmDbiTag_e_RPMDBI_OBSOLETENAME as isize,
    TRIGGERNAME = librpm::rpmDbiTag_e_RPMDBI_TRIGGERNAME as isize,
    DIRNAMES = librpm::rpmDbiTag_e_RPMDBI_DIRNAMES as isize,
    INSTALLTID = librpm::rpmDbiTag_e_RPMDBI_INSTALLTID as isize,
    SIGMD5 = librpm::rpmDbiTag_e_RPMDBI_SIGMD5 as isize,
    SHA1HEADER = librpm::rpmDbiTag_e_RPMDBI_SHA1HEADER as isize,
    INSTFILENAMES = librpm::rpmDbiTag_e_RPMDBI_INSTFILENAMES as isize,
}

impl From<Index> for DBIndexTag {
    fn from(i: Index) -> Self {
        match i {
            Index::Name => DBIndexTag::NAME,
        }
    }
}